src/models/Upload.py
# Importa las librerías y módulos necesarios.
from werkzeug.utils import secure_filename
from src.utils.Logger import Logger
from flask import flash
import os
import random
import string
import traceback

# Clase que maneja la carga y almacenamiento de imágenes.
class UploadHandler:
    def __init__(self, file, upload_folder):
        self.file = file
        self.upload_folder = upload_folder

    # Genera un nombre de archivo aleatorio para la imagen.
    def generate_random_filename(self):
        random_name = ''.join(random.choices(string.digits, k=10))
        return random_name

    # Verifica si el archivo tiene una extensión válida de imagen.
    def is_image(self, filename):
        allowed_extensions = {'png', 'jpg', 'jpeg'}
        return '.' in filename and filename.rsplit('.', 1)[1].lower() in allowed_extensions

    # Guarda la imagen en el servidor y maneja posibles errores.
    def save_image(self):
        try:
            if self.file.filename == '':
                flash("El archivo no tiene nombre.", "danger")
                return None

            if not self.is_image(self.file.filename):
                flash("El archivo no es una imagen válida.", "danger")
                return None

            random_filename = self.generate_random_filename()

            # Genera un nombre de archivo seguro utilizando la función secure_filename.
            filename = secure_filename(random_filename + os.path.splitext(self.file.filename)[1])

            # Guarda la imagen en el directorio de carga.
            self.file.save(os.path.join(self.upload_folder, filename))

        except Exception as ex:
            # Registra errores en el registro de la aplicación.
            Logger.add_to_log("error", str(ex))
            Logger.add_to_log("error", traceback.format_exc())

        return filename

# Clase que maneja el almacenamiento de la información de imágenes en la base de datos.
class UploadDB:
    def __init__(self, id_user, picture):
        self.id_user = id_user
        self.picture = picture

    # Guarda la información de la imagen en la base de datos y maneja posibles errores.
    def save_image_db(self, conn):
        cursor = conn.cursor()

        try:
            insert_query = "INSERT INTO pictures (id_user, picture) VALUES (%s, %s)"
            data = (self.id_user, self.picture)
            
            cursor.execute(insert_query, data)
            conn.commit()
            cursor.close()

        except Exception as ex:
            # Registra errores en el registro de la aplicación.
            Logger.add_to_log("error", str(ex))
            Logger.add_to_log("error", traceback.format_exc())

        finally:
            # Realiza operaciones de limpieza como el rollback y el cierre del cursor.
            conn.rollback()
            cursor.close()

src/routes/AccessRoutes.py
# Importa las librerías y módulos necesarios.
from flask import Blueprint, render_template, request, redirect, session, flash
from src.database.connection import connectionDB
from src.models.User import UserValidator, Register, Login

# Crea un objeto Blueprint llamado 'access_blueprint'.
main = Blueprint('access_blueprint', __name__)

# Define una ruta que maneja tanto las solicitudes GET como las POST.
@main.route('/', methods=['GET', 'POST'])
def access():
    if request.method == 'POST':
        if 'register-button' in request.form:
            # Obtiene datos del formulario de registro.
            fullname_register = request.form['fullname-register']
            email_register = request.form['email-register']
            username_register = request.form['username-register']
            password_register = request.form['password-register']

            # Establece una conexión a la base de datos.
            conn = connectionDB()

            # Valida los campos del formulario de registro.
            user_validator = UserValidator(fullname_register, email_register, username_register, password_register)
            validation_errors = user_validator.validate_fields(conn)

            if validation_errors:
                # Muestra un mensaje de error en la interfaz de usuario en caso de validación fallida.
                flash("Error al Registrarse, inténtalo nuevamente", "danger")
                return render_template('app/access.html', errors=validation_errors)
            
            # Registra al usuario en la base de datos.
            user_to_register = Register(fullname_register, username_register, email_register, user_validator.hash_password(password_register))
            user_to_register.register_in_db(conn)

            # Muestra un mensaje de éxito en la interfaz de usuario.
            flash("Registro de Usuario exitoso", "success")

            conn.close()
            return render_template('app/access.html')
        
        if 'login-button' in request.form:
            # Obtiene datos del formulario de inicio de sesión.
            username_login = request.form['username-login']
            password_login = request.form['password-login']

            # Establece una conexión a la base de datos.
            conn = connectionDB()

            # Intenta autenticar al usuario.
            user_login = Login(username_login, password_login)
            authenticated_user = user_login.authenticate(conn)

            if authenticated_user:
                # Almacena información de usuario autenticado en la sesión y redirige.
                session['user_id'] = authenticated_user['user_id']
                session['username'] = authenticated_user['username']
                session['fullname'] = authenticated_user['fullname']
                session['email'] = authenticated_user['email']
                return redirect('/app/gallery')
            
            # Muestra un mensaje de error en la interfaz de usuario en caso de autenticación fallida.
            flash("Usuario o contraseña incorrectos.", "danger")
        
        return render_template('app/access.html')
        
    return render_template('app/access.html')

src/routes/IndexRoutes.py
# Importa las librerías y módulos necesarios.
from flask import Blueprint, redirect

# Crea un objeto Blueprint llamado 'index_blueprint'.
main = Blueprint('index_blueprint', __name__)

# Define una ruta para la página de inicio.
@main.route('/')
def index():
    # Redirige a los usuarios a la página de la galería.
    return redirect('app/gallery')

src/templates/app/access.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='assets/logo/logo.jpg') }}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/access.css') }}">
    <title id="pageTitle">Iniciar Sesión</title>
</head>
<body>
    <main>
        <div class="container-all">
            <div class="back-box">
                <div class="back-box-login">
                    <h3>¿Ya tienes una cuenta?</h3>
                    <p>Inicia sesión para entrar en la página</p>
                    <button id="btn-login">Iniciar Sesión</button>
                </div>
                <div class="back-box-register">
                    <h3>¿Aún no tienes una cuenta?</h3>
                    <p>Regístrate para que puedas iniciar sesión</p>
                    <button id="btn-register">Regístrarse</button>
                </div>
            </div>

            <div class="login-register-container">
                <form action="{{ url_for('access_blueprint.access') }}" method="POST" class="login-form">
                    <h2>Iniciar Sesión</h2>
                    <div class="form-group">
                        <label for="username"><i class="fa fa-user"></i></label>
                        <input type="text" id="username" name="username-login" placeholder="Usuario o Email">
                    </div>
                    <div class="form-group">
                        <label for="password"><i class="fa fa-lock"></i></label>
                        <input type="password" id="password-login" name="password-login" placeholder="Contraseña">
                        <span class="password-toggle" id="password-toggle-login"><i class="fa fa-eye"></i></span>
                    </div>
                    <button type="submit" name="login-button">Iniciar Sesión</button>
                </form>

                <form action="{{ url_for('access_blueprint.access') }}" method="POST" class="register-form">
                    <h2>Regístrarse</h2>
                    <div class="form-group">
                        <label for="fullname"><i class="fa fa-user"></i></label>
                        <input type="text" id="fullname" name="fullname-register" placeholder="Nombre Completo">
                    </div>
                    <div class="form-group">
                        <label for="email"><i class="fa fa-envelope"></i></label>
                        <input type="email" id="email" name="email-register" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="username"><i class="fa fa-user"></i></label>
                        <input type="text" id="username" name="username-register" placeholder="Usuario">
                    </div>
                    <div class="form-group">
                        <label for="password-register"><i class="fa fa-lock"></i></label>
                        <input type="password" id="password-register" name="password-register" placeholder="Contraseña">
                        <span class="password-toggle" id="password-toggle-register"><i class="fa fa-eye"></i></span>
                    </div>
                    <button type="submit" name="register-button">Regístrarse</button>
                </form>
            </div>
        </div>

        {% include "includes/customs.html" %}
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{{ url_for('static', filename='js/access.js') }}"></script>
</body>
</html>

src/templates/app/index.html
{% include "includes/header.html" %}

    {% if pictures %}
        <div class="grid-container">
            {% for picture in pictures %}
            <img src="{{ url_for('static', filename='assets/uploads/pictures/' + picture['picture']) }}" alt="{{ picture['picture'] }}" class="grid-item">
            <div id="myModal" class="modal">
                <span class="close" onclick="closeModal()">&times;</span>
                <img id="modalImage" src="" alt="Imagen Modal">
                
                <div class="modal-icons">
                    <a class="prev" onclick="changeImage(-1)"><i class="fas fa-chevron-left"></i></a>
                    <a class="next" onclick="changeImage(1)"><i class="fas fa-chevron-right"></i></a>
                </div>

            </div>
            {% endfor %}
        </div>
    {% endif %}
    {% if not pictures %}
        <div class="not-image">
            <h2 class="message-title">¡Hola, <span>{{ session['username'] }}</span>!</h2>
            <p class="message-text">No has subido ninguna imagen todavía, ¡pero puedes hacerlo ahora!</p>
            <a href="{{ url_for('upload_blueprint.upload') }}" class="upload-link">Presiona aquí para subir una imagen.</a>
        </div>
    {% endif %}
    

{% include "includes/footer.html" %}

src/templates/app/pageNotFound.html
{% include "includes/header.html" %}

<div class="error-container">
    <i class="fas fa-exclamation-circle fa-7x text-danger"></i>
    <h2>¡Oops!</h2>
    <p>Página no encontrada</p>
    <p><a href="{{ url_for('index_blueprint.index') }}">Volver a la página de inicio</a></p>
</div>

{% include "includes/footer.html" %}

src/templates/app/upload.html
{% include "includes/header.html" %}

<main>

    <div class="box">
        <div class="file-box">
            <form action="/app/upload" method="POST" enctype="multipart/form-data">
                <h2>Sube una Nueva Imagen</h2>
                <label class="file-input">
                    <input type="file" id="file" accept=".jpg, .jpeg, .png" name="picture" style="display: none;">
                    <div id="drop-area" class="drop-area">
                        <i class="fas fa-cloud-upload-alt upload-icon"></i>
                        <p>Arrastra y suelta un archivo o haz clic aquí para <span>seleccionar un archivo</span>.</p>
                    </div>                    
                </label>
            </form>
        </div>
    </div>
    {% include "includes/customs.html" %}
</main>
{% include "includes/footer.html" %}