src/routes/GalleryRoutes.py
# Importa las librerías y módulos necesarios.
from flask import Blueprint, render_template, session, redirect
from src.database.connection import connectionDB
from src.utils.Logger import Logger
import traceback

# Crea un objeto Blueprint llamado 'gallery_blueprint'.
main = Blueprint('gallery_blueprint', __name__)

# Define una ruta que maneja tanto las solicitudes GET como las POST.
@main.route('/', methods=['GET', 'POST'])
def gallery():
    if 'user_id' in session:
        # Establece una conexión a la base de datos.
        conn = connectionDB()
        cursor = conn.cursor(dictionary=True)

        try:
            # Realiza una consulta para obtener las imágenes asociadas al usuario.
            select_query = "SELECT * FROM pictures WHERE id_user = %s"
            data = (session['user_id'],)

            # Ejecutar la consulta y obtener las imágenes.
            cursor.execute(select_query, data)
            pictures_results = cursor.fetchall()
        
        except Exception as ex:
            # En caso de error, registra detalles de la excepción en el registro.
            Logger.add_to_log("error", str(ex))
            Logger.add_to_log("error", traceback.format_exc())

        finally:
            # Realiza operaciones de limpieza como el rollback y el cierre del cursor.
            conn.rollback()
            cursor.close()
        
        # Renderiza la plantilla HTML de la página de la galería, pasando los resultados de las imágenes.
        return render_template('app/index.html', pictures=pictures_results, type_page="gallery")

    else:
        # Si el usuario no está autenticado, redirige al usuario a la página de inicio de sesión.
        return redirect('/app/access')

src/routes/LogoutRoutes.py
# Importa las librerías y módulos necesarios.
from flask import Blueprint, session, redirect

# Crea un objeto Blueprint llamado 'logout_blueprint'.
main = Blueprint('logout_blueprint', __name__)

# Define una ruta que maneja tanto las solicitudes GET como las POST.
@main.route('/', methods=['GET', 'POST'])
def logout():
    if 'user_id' in session:
        # Si el usuario está autenticado, borra la sesión del usuario.
        session.clear()
        # Redirige al usuario a la página de inicio de sesión o a donde desees.
        return redirect('/app/access')
    else:
        # Si el usuario no está autenticado, redirige al usuario a la página de inicio de sesión.
        return redirect('/app/access')

src/templates/includes/customs.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>
<link rel="stylesheet" href="../../static/css/customs.css">
<body class="custom-container">
    
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for message in messages %}
            <div class="toast toast-{{ message[0] }}">
                <div class="toast-content">
                    <i class="fas fa-solid {% if 'success' in message[0] %} fa-check check {% endif %} {% if 'warning' in message[0] %} fas fa-exclamation-circle circle {% endif %} {% if 'danger' in message[0] %} fas fa-exclamation-triangle triangle {% endif %}"></i>
                    <div class="message">
                        <span class="text text-1">{{ message[0] }}</span>
                        <span class="text text-2">{{ message[1] }}</span>
                    </div>
                </div>
                <i class="fa-solid fa-xmark close"></i>
                <div class="progress progress-{{ message[0] }}"></div>
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

</body>
<script src="../../static/js/customs.js"></script>

src/templates/includes/footer.html
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
    <script src="https://unpkg.com/imagesloaded@5/imagesloaded.pkgd.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="{{ url_for('static', filename='js/gallery.js') }}"></script>
    <script src="{{ url_for('static', filename='js/upload.js') }}"></script>
    <script src="{{ url_for('static', filename='js/header.js') }}"></script>
    <script src="{{ url_for('static', filename='js/customs.js') }}"></script>
    
</body>
</html>

src/templates/includes/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='assets/logo/logo.jpg') }}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/upload.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/gallery.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/customs.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/pageNotFound.css') }}">
    <title>
        gallery | 
        {% if type_page == 'gallery' %} Galeria {% endif %}
        {% if type_page == 'upload' %} Subir {% endif %}
        {% if type_page == 'pageNotFound' %} Pagina 404 {% endif %}
    </title>
</head>

<header class="header">
    <div class="logo">
        <a href="{{ url_for('gallery_blueprint.gallery') }}">
            <p class="logo-txt">gallery</p>
        </a>
    </div>
    <div class="menu-toggle" id="menu-toggle">
        <i class="fas fa-bars" id="menu-icon"></i>
        <i class="fas fa-times" id="close-icon" style="display: none;"></i>
    </div>
    <nav class="menu-navegacion">
        <a href="{{ url_for('gallery_blueprint.gallery') }}"><i class="fas fa-images"></i> Galeria</a>
        <a href="{{ url_for('upload_blueprint.upload') }}"><i class="fas fa-upload"></i> Subir</a>
        <a href="{{ url_for('logout_blueprint.logout') }}"><i class="fas fa-sign-out-alt"></i> Salir</a>
    </nav>
</header>